//
// Created by 喻如辰 on 2020/11/10.
//

#ifndef DATA_STRUCTURE_AND_ALGORITHM_ANALYSIS_GLOBAL_H
#define DATA_STRUCTURE_AND_ALGORITHM_ANALYSIS_GLOBAL_H

enum StatusCode {SUCCESS = 0, FAIL, UNDER_FLOW, OVER_FLOW,
    RANGE_ERROR, DUPLICATE_ERROR,NOT_PRESENT, ENTRY_INSERTED, ENTRY_FOUND, VISITED, UNVISITED};

#endif //DATA_STRUCTURE_AND_ALGORITHM_ANALYSIS_GLOBAL_H
