//
// Created by 喻如辰 on 2020/10/11.
// (循环)顺序队列，Sequence_Queue
//

#ifndef DATA_STRUCTURE_AND_ALGORITHM_ANALYSIS_SEQQUEUE_H
#define DATA_STRUCTURE_AND_ALGORITHM_ANALYSIS_SEQQUEUE_H

#define DEFAULT_SIZE 10

enum StatusCode {SUCCESS = 0, FAIL, UNDER_FLOW, OVER_FLOW,
    RANGE_ERROR, DUPLICATE_ERROR,NOT_PRESENT, ENTRY_INSERTED, ENTRY_FOUND, VISITED, UNVISITED};

// todo: Sequence Queue

#endif //DATA_STRUCTURE_AND_ALGORITHM_ANALYSIS_SEQQUEUE_H
